spring:
  datasource:
    url: jdbc:h2:file:./db/testProject;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password:
    driver-class-username: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      # console view at localhost:8080/console
      path: /console

logging:
  level:
    org.springframework.web: INFO
    evgenii: DEBUG
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: logs/logs.log
